# 
# docker-compose.yml — определяет сервисы для разработки и тестирования.

#Что нужно сделать:
#  - Настроить сервисы для:
#      - PostgreSQL (или MySQL) с начальной базой.
#      - Приложения Spring Boot (если нужно).
#  - Открыть нужные порты (например, 5432, 8080).
#  - Настроить volume для хранения данных БД.

services:
  app:
    container_name: bank_rest
    build: ./
    ports:
      - '8080:8080'
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/bank_rest
      - SPRING_DATASOURCE_USERNAME=db_admin
      - SPRING_DATASOURCE_PASSWORD=p@ssw0rd
      - JPA_HIBERNATE_DDL_AUTO=none
      - JPA_SHOW_SQL=true
    networks:
      network:
  db:
    image: postgres:17
    container_name: postgres
    environment:
      - POSTGRES_USER=db_admin
      - POSTGRES_PASSWORD=p@ssw0rd
      - POSTGRES_DB=bank_rest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      network:
volumes:
  postgres_data:
networks:
  network: